name: 10 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  *name Of job, free choice, could also give a name
  build:
    # required to fix an issue we had Ehen test results failed because
    # Checks: write and pull-requests: write were needed
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    # runner
      runs-on: ubuntu- latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    # compile
    - name: Build With Maven
      run: mvn clean package -B -Dmaven.test.skip
    - run: mkdir candidate-binary && cp target/*.jar candidate-binary
    # test
    - name: Test With Maven
      run: mvn test
    - run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results
    - uses: actions/upload-artifact@v3
      with:
        name: Application-Binary
        path: candidate-binary
     - uses: actions/upload-artifact@v3
       with:
          name: Test-Results
          path: test-results
     - name: Publish Test Results
       uses: EnricoMi/publish-unit-test-result-action@v2.0.0
       if: always()
       with:
        junit_files: "test-results/**/*.xml"
